In [1]:
#파이썬으로 배우는 머신러닝

#머신러닝 변천사
#고전적 인공지능 - 신경망 - 머신러닝 - 빅데이터 - 딥러닝

#파이썬에서 머신러닝을 테스트 및 구현하려면
#numpy, scipy, pandas, matplotlib, scikit-learn 등의 필요
#부수적으로 mglearn 패키지도 설치할 것

import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
from sklearn import datasets
import mglearn

iris = datasets.load_iris()
#boston
#wine
#cancer
#diabetes
digits = datasets.load_digits() # 숫자 필기 이미지
# lands = datasets.fetch_20newsgroups() #뉴스 그룹 문자자료
# faces = datasets.fetch_lfw_people() #얼굴이미지

#훈련데이터와 테스트데이터 생성하기 지도학습으로 머신러닝 시스템 구축시
#레이블된 데이터가 필요 이러한 데이터를 2개 그룹으로 나눠 작업하는데
#특정 작업을 위한 모델 생성 - 훈련데이터
#생성된 모델의 작동여부 파악 - 검증데이터

#scikit-learn에서는 이러한 작업을 위해 train_test_split 함수제공
#데이터는 x로 레이블은 y로 표기함
print(iris.data[:5,:])
print(iris.target[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [2]:
#train_test_split으로 train, test으로 나누기
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, train_size=0.7, test_size=0.3, random_state=0)
#훈련데이터 레이블 X_train, y_train
#테스트데이터 레이블 X_test, y_test

# print('훈련데이터 개수', X_train.shape)
# print('훈련데이터 개수', y_train.shape)
# print('검증데이터 개수', X_test.shape)
# print('검증데이터 개수', y_test.shape)
#
# irisdf = pd.DataFrame(X_train, columns=iris.feature_names)
# pd.plotting.scatter_matrix(irisdf, c=y_train, s=50, cmap=mglearn.cm3, alpha=0.8, figsize=(10,10))
# plt.show()

#KNN분류 알고리즘
#KNN 예제용 데이터셋 생성
X, y = mglearn.datasets.make_forge()
print('knn 예제 데이터', X, y)

# mglearn.discrete_scatter(X[:,0], X[:,1],y)
# plt.show()
# 
# #새로운 데이터 3개를 추가해서 KNN분류분석 추가된 데이터와 가장 가까운 훈련데이터 k개를 찾음.
# #단, k가 3이상인 경우 레이블을 정하기 위한 다수결 채택
# #즉, 더 많은 이웃을 가진 데이터가 레이블로 정해짐.
# mglearn.plots.plot_knn_classification(n_neighbors=1)
# plt.show()
# 
# mglearn.plots.plot_knn_classification(n_neighbors=3)
# plt.show()

#kNN 예제용 데이터셋을 이용해서 KNN알고리즘 적용
# X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=0) #데이터를 자동으로 7:3으로 나눔
# print('X데이터 크기', X.shape)
# print('훈련 x데이터', X_train.shape)
# print('훈련 y데이터', y_train.shape)
# 
# from sklearn.neighbors import KNeighborsClassifier #KNN분류기 선언
# knnclf = KNeighborsClassifier(n_jobs=3) #k분류기 k값 설정
# 
# knnclf.fit(X_train, y_train) #모델 학습
# print('모델 검증', knnclf.predict(X_test), y_test)
# print('모델 검증 정확도', knnclf.score(X_test, y_test))
#iris 데이터로 KNN
iris = datasets.load_iris()
X = iris.data
y = iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, test_size=0.3, random_state=0)
print('X데이터 크기', X.shape)
print('훈련 x데이터', X_train.shape)
print('훈련 y데이터', y_train.shape)

knnclf = KNeighborsClassifier(n_jobs=2) #k분류기 k값 설정
knnclf.fit(X_train, y_train) #모델 학습

print('모델 검증', knnclf.predict(X_test), y_test)
print('모델 검증 정확도', knnclf.score(X_test, y_test))


knn 예제 데이터 [[ 9.96346605  4.59676542]
 [11.0329545  -0.16816717]
 [11.54155807  5.21116083]
 [ 8.69289001  1.54322016]
 [ 8.1062269   4.28695977]
 [ 8.30988863  4.80623966]
 [11.93027136  4.64866327]
 [ 9.67284681 -0.20283165]
 [ 8.34810316  5.13415623]
 [ 8.67494727  4.47573059]
 [ 9.17748385  5.09283177]
 [10.24028948  2.45544401]
 [ 8.68937095  1.48709629]
 [ 8.92229526 -0.63993225]
 [ 9.49123469  4.33224792]
 [ 9.25694192  5.13284858]
 [ 7.99815287  4.8525051 ]
 [ 8.18378052  1.29564214]
 [ 8.7337095   2.49162431]
 [ 9.32298256  5.09840649]
 [10.06393839  0.99078055]
 [ 9.50048972 -0.26430318]
 [ 8.34468785  1.63824349]
 [ 9.50169345  1.93824624]
 [ 9.15072323  5.49832246]
 [11.563957    1.3389402 ]] [1 0 1 0 0 1 1 0 1 1 1 1 0 0 1 1 1 0 0 1 0 0 0 0 1 0]
X데이터 크기 (150, 4)
훈련 x데이터 (105, 4)
훈련 y데이터 (105,)


C:\Users\TJ\venv\py36\lib\site-packages\sklearn\utils\deprecation.py:77: DeprecationWarning: Function make_blobs is deprecated; Please import make_blobs directly from scikit-learn
  warnings.warn(msg, category=DeprecationWarning)


NameError: name 'KNeighborsClassifier' is not defined

In [3]:
#새로운 데이터 예측 - 데이터셋에 존재하지 않는 데이터
# new_iris = np.array([[1,1,1,1]]) #예측한 품종 :  ['setosa']
new_iris = np.array([[20,20,20,20]]) #예측한 품종 :  ['virginica']
result = knnclf.predict(new_iris)
print('새로운 데이터로 예측', result)
print('예측한 품종 : ',  iris['target_names'][result])


NameError: name 'knnclf' is not defined

In [4]:
#모델정확도 측정 - confusion_matrix
from sklearn.metrics import confusion_matrix
cfm = confusion_matrix(y_test, knnclf.predict(X_test))
print(cfm)
#오차행렬을 그래프로 표시
import seaborn as sns

# sns.heatmap(cfm, square=True, annot=True, cbar=False, fmt='g', cmap='YlGnBu')
# plt.xlabel('predict')
# plt.ylabel('versicolor/verginica/setosa')
# plt.show()


NameError: name 'knnclf' is not defined

In [5]:
#타이타닉 데이터셋을 이용하 KNN분석 1
#승객명, 좌석등급, 나이, 성별, 생존여부
#iris 데이터로 KNN

import pandas as pd
# titanic = sns.load_dataset
titanic = pd.read_csv('C:/Users/TJ/Google 드라이브/학습자료/프로그래밍/data science/Sample data/r/titanic.csv',  engine='python')
print('타이타닉 데이터1\n', titanic.head())
print('타이타닉 데이터2\n', titanic.tail())

titanic_data = titanic[:, 1:4]
titanic_target = titanic[:, 4]

print('추출된 데이터', titanic_data)
print('추출된 데이터', titanic_target)

#결측치 처리
print(titanic_data.isnull().sum())
# 1. 제거, 2. 0으로 대체, 3. 평균, 최대, 최소로 대체
# 제거
titanic_data = titanic_data.dropna() #1
titanic_data = titanic_data['Age'].dropna() #2

#카테고리 특성을 수치형으로 변환
#좌석등급 1st, 2nd, 3rd => 1,2,3
#성별 male, female => 0,1

for i in range(len(titanic_data)):
    if titanic_data['PClass'][i] == '1st':
        titanic_data['PClass'] = 1
        



# X = titanic.get
# y = titanic.target
# X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, test_size=0.3, random_state=0)
# print('X데이터 크기', X.shape)
# print('훈련 x데이터', X_train.shape)
# print('훈련 y데이터', y_train.shape)
# 
# knnclf = KNeighborsClassifier(n_jobs=2) #k분류기 k값 설정
# knnclf.fit(X_train, y_train) #모델 학습
# 
# print('모델 검증', knnclf.predict(X_test), y_test)
# print('모델 검증 정확도', knnclf.score(X_test, y_test))


타이타닉 데이터1
    PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN   

TypeError: unhashable type: 'slice'